# Java
### 프로그램 오류
* #### 컴파일 에러 : 컴파일 시에 발생하는 에러
* #### 런타임 에러 : 실행 시에 발생하는 에러
* #### 논리적 에러 : 실행은 되지만, 의도와 다르게 동작하는 것
* #### 에러(error) : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
* #### 예외(exception) : 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류
* #### 모든 예외의 최고 조상은 Exception클래스이며, 이 클래스 또한 Object클래스의 자손이다.
### 예외처리하기 (try-catch문)
* #### 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하기 위함
```java
try {
    // 예외가 발생할 가능성이 있는 문장
} catch (Exception1 e1) {
    //Exception1이 발생했을 경우, 이를 처리하기 위한 문장
} catch (Exception2 e2) {
    //Exception2이 발생했을 경우, 이를 처리하기 위한 문장
}
```
* #### try블럭 내에서 예외가 발생한 경우
  * #### 1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
  * #### 2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속 수행한다.
  * #### (만일 일치하는 catch블럭을 찾지 못하면 예외는 처리되지 못한다.)
* #### try블럭 내에서 예외가 발생하지 않은 경우
  * #### catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.

```java
// 예외의 발생원인 파악
printStackTrace() // 예외발생 당시에 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
getMessage() // 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
```

```java
try {
    //어쩌구 저쩌구
} catch (Exception1 | Exception2 e) { // 멀티 catch블럭 (JDK1.7부터)
    e.printStackTrace();
}
```
### 예외 발생시키기
```java
//연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 생성
Exception e = new Exception("고의로 발생시켰다");

//키워드 throw를 이용해서 예외를 발생
throw e;

throw new Exception("고의로 발생시켰다."); // 이렇게 한줄로 표현 가능
```
### 메서드 예외 선언
```java
// 메서드 내에서 발생할 수 있는 예외를 적어준다.
void method() throws Exception1, Exception2, Exception3 {
    //메서드의 내용
}
```

### finally블럭
```java
try{
    // 예외가 발생할 가능성 있는 문장
} catch (Exception1 e1){
    // 예외 처리
} finally {
    // 예외의 발생여부와 관계없이 항상 수행
}